version: "3.9"
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: reservation
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_USER: kidari
      MYSQL_PASSWORD: kidari_pass